- application/app.py
Redirect PosixPath to WindowsPath on Windows to fix https://github.com/arc53/docsgpt/issues/12.
> Redirect PosixPath to WindowsPath on Windows.

- application/templates/index.html
Longchain => LangChain
completely went over my head, my bad
> Fix LangChain name inconsistancies

- scripts/ingest_rst.py
- scripts/ingest_rst_sphinx.py
Calculates number of tokens/user cost and requires user permission to proceed.
User permission bypass is built-in to allow for non-human users.
> Add cost estimate feature

- scripts/ingest_rst.py
- scripts/ingest_rst_sphinx.py
Sorry for the additional trailing whitespace changes. Let me know if you'd like me to remove those.
> Adding docs location argument to ingest scripts

- application/static/src/authapi.js
Added descriptive variable names and reduced the number of DOM manipulations by storing references to elements that are used lots of times.
> updated authapi.js

- scripts/parser/file/rst_parser.py
Some additional filters for rst parsing
> Directives + Interpreted

- .gitignore
- scripts/ingest_rst_sphinx.py
It would be great if it could support more plain-text-like formats such as markdown, etc. I'm not sure how this repository plans to accomplish this, but I can share my solution for markdown.
> feat: compatible with markdown

- .github/workflows/ci.yml
Signed-off-by: Carson Yang <yangchuansheng33@gmail.com>
> Add Docker Image CI support

- frontend/src/App.tsx
- frontend/src/Avatar.tsx
- frontend/src/Navigation.tsx
- frontend/src/assets/send.svg
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- frontend/src/conversation/ConversationInput.tsx
- frontend/src/models/misc.ts
- frontend/tailwind.config.cjs
This PR adds UI components for conversations. It also simplifies ApiKeyModal state management(brings it closer)
Below snapshots are with hardcoded conversation.
Desktop View(open navigation):
Desktop View(closed navigation):
Mobile View(open navigation):
Mobile View(closed navigation):
> Adds Conversation components & simplifies APIKey modal visibility

- frontend/src/App.tsx
- frontend/src/Navigation.tsx
This PR restores the sidebar and conversation transition.
> Restores side bar and conversation transition

- frontend/src/Hero.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- frontend/src/conversation/conversationModels.ts
- frontend/src/conversation/conversationSlice.ts
- frontend/src/store.ts
When messages exists in redux store:
when no message exist in redux store:
> Adds Hero welcome page, introduces conversation slice and wires conversation UI with redux 

- scripts/ingest.py
- scripts/parser/java2doc.py
- scripts/parser/js2doc.py
- scripts/parser/py2doc.py
3 languages added, works well with python. Java and Js require additional revieving
> Code_to_dict

- frontend/src/App.tsx
- frontend/src/Navigation.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/hooks.ts
- frontend/src/preferences/APIKeyModal.tsx
This PR does following:
1]Adds tap elsewhere feature as suggested by @tenokami .
2]Adds hover effect on send icon.
> Nick's list : 8 & 10

- frontend/src/About.tsx
- frontend/src/Hero.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/tailwind.config.cjs
Fixes 3, 4, 6 & 7 from [Nick's List](https://github.com/arc53/DocsGPT/issues/131)
> Nick list : 3, 4, 6, 7

- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- frontend/src/conversation/conversationApi.ts
- frontend/src/conversation/conversationSlice.ts
As soon as user interacts with feedback feature 
-> redux store gets updated
-> call to api layer is made
-> if the call to api layer fails with a failed promise the feedback state in redux store is reverted to last value.
> wires up feedback event handler with redux store

- .github/workflows/sync_fork.yaml
Add the ability to schedule sync fork for the project.
> sync fork for workflow

- README.md
- application/wsgi.py
- docker-compose-dev.yaml
- frontend/.env.development
Previous instructions missed some steps so I added them for transparency.
> Updated readme for development run

- .github/workflows/ci.yml
- .github/workflows/cife.yml
https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
> fix workflow: login to GHCR according to the GH documentation

- .github/workflows/ci.yml
- .github/workflows/cife.yml
https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action
> fix workflow: adjust permissions according to documentation

- scripts/parser/file/bulk.py
Resolves this issue https://github.com/arc53/DocsGPT/issues/240#issue-1714665631
> updating the bulk ingest file metadata logic

- .env-template
- application/.env_sample
- application/app.py
- application/core/settings.py
- docker-compose.yaml
- scripts/parser/open_ai_func.py
A bit dirty commit, but I had a very aggressive formatting rule.
In the app.py the meaningful changes are lines 241-249.
Please review the other files thoroughly.
> Azure support #199

- README.md
unordered list in "### Run the backend" had a typo in the md format
> Fix md rendering

- application/requirements.txt
1. remove unnecessary dependencies to speed up the build and reduce the download volume.
2. upgrade a couple of dependencies.
> fixes for requirements.txt

- .github/workflows/pytest.yml
Add information about test coverage to pull requests as a comment.
> count test coverage

- docs/pages/Developing/API-docs.md
you can fixes in the same way other pages
> fix syntax highlightning

- frontend/src/About.tsx
- frontend/src/Modal/index.tsx
- frontend/src/Navigation.tsx
- frontend/src/preferences/APIKeyModal.tsx
- frontend/src/preferences/SelectDocsModal.tsx
- frontend/src/upload/Upload.tsx
Following changes were implemented: 
- Button border and onHover border consistency changes as directed in issue #279 
- Arrow icon positioning in source docs dropdown
- APIKeyModal, SelectDocsModal and Modal border roundedness adjusted to make combined elements fit together better.
> UI Improvements, implements task 3 in issue #279

- docs/pages/Guides/My-AI-answers-questions-using-external-knowledge.md
Corrected grammatical errors and spelling errors in : docs/pages/Guides/My-AI-answers-questions-using-external-knowledge.md
> Grammatical corrections

- frontend/src/Navigation.tsx
> Adding tab to documentation in Navigation bar

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
fixes #380  Added the following templates:
- 🚀  Feature request templates.
- 🐛 Bug report templates.
- 🔗 PR templates.
> feat: create issue template forms to ensure consistency in issue and pr formats

- README.md
- docs update, added contributors images in the readme file 
- when every contributor sees their name, in the project readme files, i believe they somwhat relates more to the project and also I think makes up the part of the project
> Added Contributors Images in Readme.md

- docs/pages/Deploying/Quickstart.md
- Fixed a few issues in the document
> [Docs] Update Quickstart.md

- docs/pages/Deploying/Hosting-the-app.md
- docs/pages/Deploying/Quickstart.md
- docs/pages/Developing/API-docs.md
- docs/pages/Extensions/Chatwoot-extension.md
- docs/pages/Extensions/react-widget.md
- docs/pages/Guides/Customising-prompts.md
- docs/pages/Guides/How-to-train-on-other-documentation.md
- docs/pages/Guides/How-to-use-different-LLM.md
Some docs improve
Improved readability and fix some typo 
> Improved docs readability and fix some typo.

- README.md
- docs/pages/Deploying/Quickstart.md
- docs/pages/Developing/API-docs.md
- docs/pages/Guides/Customising-prompts.md
- docs/pages/Guides/How-to-train-on-other-documentation.md
Docs update
- Corrected the wrapper name, added links and made other minor changes.
Closes: #455 
> correct wrapper, typos; add links

- CONTRIBUTING.md
- HACKTOBERFEST.md
- README.md
Improved docs.
There were many typos, styling and wording inconsistencies in the docs. I tried to fix the most that I could find. Open to edits.
> improved CONTRIBUTING.MD, README.MD, HACKTOBERFEST.MD

- application/llm/sagemaker.py
For some reason tests on github actions are failing
> Fix tests on sagemaker.py

- frontend/src/Hero.tsx
- frontend/src/conversation/Conversation.tsx
- Bug fix- Close- #459 
- Actually, the Hero section's design does not match with the respective Figma UI. So, I changed the design properties.
**Before Fix:**
**After Fix:**
> Hero section's figma UI changes

- README.md
- ✅ Added code of conduct section to documentation.
- ✅ Added license section into the repository.
- ✅ Fixed some Typos.
- #453
> Update README.md -- Fixed #453

- CONTRIBUTING.md
Improved the `CONTRIBUTING.md` file by making the heading **bold**
To improve the user experience.
> Make text bold

- frontend/src/About.tsx
> 🪛 Fix: About us page margin

- CONTRIBUTING.md
- HACKTOBERFEST.md
- README.md
Improved README, CONTRIBUTING, HACKTOBERFEST md files by adding necessary 15+ links for navigation to users easily.
Kindly review and merge the same.
Thank you!
> Improved docs - readme , contributing and hacktoberfest files

- README.md
Docs update
Issue #505 
Added license links to readme.md
> add license link to readme.md

- docs/pages/Deploying/Hosting-the-app.md
- docs/pages/Deploying/Quickstart.md
- docs/pages/Developing/API-docs.md
- docs/pages/Extensions/Chatwoot-extension.md
- docs/pages/Extensions/react-widget.md
- docs/pages/Guides/Customising-prompts.md
- docs/pages/Guides/How-to-train-on-other-documentation.md
- docs/pages/Guides/How-to-use-different-LLM.md
- docs/pages/Guides/My-AI-answers-questions-using-external-knowledge.md
The markdowns in ./docs are updated with proper grammar and punctuation.
No big issue, just improvising and making the documentation accurate.
> Grammar and punctuations improved

- docs/pages/Guides/My-AI-answers-questions-using-external-knowledge.md
- **What kind of change does this PR introduce?** (docs update)
docsgpt -> DocsGPT
Added bullet points to the steps of **To adjust the DocsGPT in our way.**
> Updated My-AI-answers-questions-using-external-knowledge.md

- README.md
Docs update.
In `Development environments`, the instruction steps are incorrect. Correct to make it work.
None.
> Correct instructions in `Development environments`

- frontend/src/conversation/ConversationBubble.tsx
Makes the UI better by fixing the  position of Copy, Like, Dislike at the top of the message(answer or bot response)
The Change fixes #536 
- A demo to the change
> UI bug fixed - Placed the feedback/copy buttons at the top

- frontend/src/Navigation.tsx
Fixes updates that are chaotic and breaking change on delete
> fix update and delete bug

- CONTRIBUTING.md
- Updating the UI of DocsGPT in Figma.
- Solving issue #357.
> Closing #357 using CONTRIBUTING.md

- CONTRIBUTING.md
Docs update
For user to easily read as not having it as  a sperate point was to be difficult to read with other content provided.
- before:
- After:
> [Docs] :Enhance Tech Stack Overview with Emojis and Bullet Points 

- docs/pages/Deploying/Hosting-the-app.md
docs update
This change was needed to improve the clarity, structure, and user-friendliness of the self-hosting guide for DocsGPT on Amazon Lightsail. The previous documentation was revised to address user feedback and provide a more comprehensive and informative guide for self-hosting.
> Enhanced Documentation for Self-Hosting DocsGPT on Amazon Lightsail

- README.md
- docs/pages/Deploying/Quickstart.md
> Dhruvkadam22 patch 5

- CONTRIBUTING.md
docs update
Fixed: #578
This Pull Request aims to enhance our contributing guidelines and includes necessary code to improve the contributor experience. The updated guidelines provide clearer instructions and expectations for potential contributors, making it easier for them to participate effectively in this project. The code changes ensure the seamless integration of these guidelines into our repository.
> Adds contributing guidelines with steps

- docs/pages/Deploying/Quickstart.md
docs update
Enhance user experience and clarity.
Provide platform flexibility for Windows users.
Add context for the Chrome extension.
Minimize potential issues with Docker configuration.
> Quickstart: Enhanced Documentation for Launching DocsGPT and Installing Chrome Extension

- docs/pages/Deploying/Hosting-the-app.md
> Fixed Typo

- frontend/src/conversation/Conversation.tsx
Small fix of footer layout 
Screenshots with actual and updated layout here: https://github.com/arc53/DocsGPT/issues/593
To keep layout logically correct and prevent possible bugs with footer(text under sidebar) after implement i18n
> [FE]Fix footer width ob md+ screens

- docs/README.md
- docs/package.json
fix and docs update
To setup  Nextra-DocsGPT docs  locally 
addd missing script in package.json:
> FIX: added script in package.json of docs and added instructions to run nextra-DocsGPT locally

- frontend/src/Navigation.tsx
> fix: Direction of dropdown arrow corrected

- docs/pages/Deploying/Hosting-the-app.md
**This PR adds a new deployment guide for Civo Compute Cloud.**
**This change was needed as it fixes #632** 
**The new article has been published on Dev.to and is live for all audience.**
> Added Civo Cloud Deployment option.

- docs/pages/Developing/API-docs.md
> Enhancement: Improve API Endpoint Documentation

- docs/README.md
This PR introduces the design of the **Settings UI** for DocsGPT which contains general, prompts, documents and widgets page. This PR fixes the issue #547 
This change was needed because DocsGPT currently has no settings menu. Thus, I have designed the settings page UI in Figma file.
Link to the figma file is: https://www.figma.com/file/u8U4GbsmzjvGpuxoOz3DKY/docsgpt-settings-ui?type=design&node-id=19%3A179&mode=design&t=UJ92uAyKhNbTlpep-1
> Design the Settings UI

- docs/pages/Extensions/Chatwoot-extension.md
> Enhanced Chatwoot-Extension

- frontend/src/conversation/ConversationBubble.tsx
- **What kind of change does this PR introduce?** Bugfix
- **Why was this change needed?** Fixes #666
> Fix something went wrong message bubble

- CONTRIBUTING.md
- This PR is a docs update. 
- I have added two more steps in the workflow, to give a clear instructions to contribute to this repo smoothly for new contributors.
> Updated workflow of Contributing.md

- frontend/src/Navigation.tsx
> Fixed overflow

- CODE_OF_CONDUCT.md
Docs Update
To improve the readability and understanding of the CODE_OF_CONDUCT.md file for contributors.
Fixed minor issues so that the CODE_OF_CONDUCT.md  is error free.
> Fixed Typos and minor issues in CODE_OF_CONDUCT.md 

- docs/pages/Extensions/react-widget.md
> Enhancement: Update react-widget.md docs

- README.md
updated the documentation link of Vite and React in the Readme file
> [Add] Vite and react documentation link

- application/api/answer/routes.py
- application/llm/anthropic.py
- application/llm/llm_creator.py
- application/requirements.txt
- docker-compose.yaml
- tests/llm/test_anthropic.py
> anthropic LLM

- docs/pages/Developing/API-docs.md
This PR introduces the design of the Upload from remote sources UI for DocsGPT which contains a modal menu through which the user can upload their documentation from other sources like Github, Sitemap, etc. This PR fixes the issue https://github.com/arc53/DocsGPT/issues/548
This change was needed because DocsGPT does not have this type of menu from which user can upload docs from other sources, currently. Thus, I have designed the Upload from remote sources UI in a Figma file.
This is the link to the figma file: https://www.figma.com/file/uGf3twL3OHFSIQBgVVn6O8/docsgpt-upload-ui?type=design&node-id=0%3A1& …
> Design the Remote sources upload menu UI

- docs/pages/Guides/Customising-prompts.md
- docs/pages/Guides/How-to-train-on-other-documentation.md
> Enhancement: Updated Train other docs

- docs/pages/Guides/Customising-prompts.md
docs update
Enhanced the Customization.md
> Enhanced Guides/Customization.md

- docs/pages/Guides/How-to-use-different-LLM.md
This PR introduces update on Guide of `How-to-use-different-LLMs.md` in **docs**, to know what are the available models to use in .env file,
From the issue #687 configuring the models and knowing the available models are unclear.
> Fix Guide: How to use other LLMS

- docs/pages/Deploying/Hosting-the-app.md
**This PR adds a new deployment guide for DigitalOcean Droplet.**
**This change was needed as it fixes #649** 
**The new article has been published on Dev.to and is live for all audiences.**
> Add DigitalOcean Droplet Hosting solution to Hosting-the-app.md

- docs/pages/Developing/API-docs.md
Revising request sample for `/api/delete_old` in API-docs.
Enhancing understanding by audience in having clear API documentation.
> docs: refer delete_old sample docs_check comments API-docs

- frontend/src/preferences/preferenceApi.ts
- frontend/src/preferences/preferenceSlice.ts
- frontend/src/store.ts
> Add getLocalPrompt and setLocalPrompt functions to preferenceApi.ts

- frontend/src/conversation/ConversationBubble.tsx
- Bug Fix
<br>
- Issue: https://github.com/arc53/DocsGPT/issues/769
- Correct text overflow
<br>
- Added ```text-black``` in the ```className``` 
- **```ConversationBubble.tsx```** (frontend/src/conversation/ConversationBubble.tsx)
> fix: API docs text overflow

- application/requirements.txt
- scripts/requirements.txt
> fix: Remove py==1.11.0 from requirements.txt

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/Hero.tsx
- frontend/src/Login/ForgotPass.tsx
- frontend/src/Login/Login.tsx
- frontend/src/Login/ResetCode.tsx
- frontend/src/Login/Signup.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- Feature: This Pr Aims to develop a new Page for Signup and Signin 
- Video
https://github.com/arc53/DocsGPT/assets/85656999/a2f8dff3-a955-4c0a-a633-eefed4425434
> Creating a Seprate Page for Signup and Signin

- docs/pages/Deploying/Hosting-the-app.md
**This PR adds a new deployment guide for Kamatera Performance Cloud.**
**This change was needed as it fixes #810** 
**The new article has been published on Dev.to and is live for all audiences.**
> Added new Deployment Guide for Kamatera Performance Cloud

- frontend/src/Navigation.tsx
Fixes #814 
Sidebar components at the bottom overflowed out of screen as the length of Chat history increased
- Made some height adjustments with respect to Screen height, added scrollbar to handle overflow 
- This is how it looks now!
> adding responsive sidebar

- frontend/src/conversation/conversationApi.ts
- frontend/src/conversation/conversationSlice.ts
Streaming sources in the message stream is often missed
Integrated new endpoint /api/search in the Client side which response with the array of sources
> integrate /api/search endpoint, get sources post stream

- application/api/answer/routes.py
- frontend/src/conversation/conversationApi.ts
- frontend/src/conversation/conversationSlice.ts
Search docs using /api/search when Using Streaming response in the frontend
> Search docs not inside the /stream in the stream request

- frontend/src/Navigation.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/conversationApi.ts
- frontend/src/conversation/conversationSlice.ts
- frontend/src/hooks/index.ts
* Added abort() method if there is change in conversation id
* useRef hook to call independent instance of ```dispatch(fetchAnswer({ question }))```
* Added condition checks in case the request gets rejected with explicit abort.
* Fixed unexpected behaviour of Dark Theme
* Enhance user experience
Request gets rejected through ```abort()``` in case of navigating to other conversations on history
> Fix : error on changing conversation while streaming answer

- frontend/src/upload/Upload.tsx
- frontend/tailwind.config.cjs
Adding the feature to upload docs via Source URL.
To provide option to upload documents from the source link.
*  Demo
* On opening the dropdown
> adding remote uploads tab

- application/core/settings.py
- application/llm/llm_creator.py
- application/llm/premai.py
Feature
Adds support for https://www.premai.io/
> Add PremAI LLM implementation

- application/llm/docsgpt_provider.py
> fix: docsgpt provider

- mock-backend/package-lock.json
- mock-backend/package.json
- mock-backend/src/server.js
* Fixes #853 
* Streamed a sample message response at POST /stream.
* Created a sample route for POST /search to fetch sources.
* To test the frontend with the Mock server
> Message Streaming with the Mock Server

- .gitignore
- application/parser/file/bulk.py
- application/parser/token_func.py
- frontend/src/conversation/Conversation.tsx
> Fixing ingestion metadata grouping

- frontend/src/Navigation.tsx
- frontend/src/Setting.tsx
- frontend/src/components/Dropdown.tsx
- frontend/src/components/SourceDropdown.tsx
- frontend/src/upload/Upload.tsx
https://github.com/arc53/DocsGPT/assets/47355538/34d9eafc-57a5-49bd-9d06-43fbc0995726
> fix: issue #157

- frontend/src/Hero.tsx
- frontend/src/Navigation.tsx
- frontend/src/index.css
* Customised Scroll bar for dark mode as well.
* Fixes the hero component which  was not scrollable till the bottom in mobile and tab width
* Improves user interface, fixes UI bugs.
Scrollbar design
> Customised Scrollbar, fixed: Hero wasn't completely scrollable in Mobile

- application/api/answer/routes.py
- application/core/settings.py
There is a weird only partly working behaviour with the model_name selection. I fixed it and added another setting to configure — MODEL_NAME.
I couldn't select gpt-4 model for OpenAI. Now I can.
Pretty small fix.
> Fix model selection at least for openAI LLM_NAME

- frontend/src/store.ts
> Fix parsing issue with chunks in store.ts

- docs/pages/Developing/API-docs.md
A description of 3 more api methods in documentation.
New methods were introduced
> api update

- frontend/src/Setting.tsx
- frontend/src/components/Dropdown.tsx
- frontend/src/preferences/PromptsModal.tsx
- frontend/src/upload/Upload.tsx
- dropdown for selecting prompts and editing/deleting them as per Figma design
- modals for adding and editing prompts
> feat: added prompts section under general in settings

- application/api/user/routes.py
- frontend/src/Setting.tsx
- frontend/src/components/Dropdown.tsx
- frontend/src/upload/Upload.tsx
- Option to select number of chunks and prompt.
- Changes made in Dropdown component: added two parameters fullWidth and alignMiddle of type boolean.
- To give more flexibility to user.
- Better UX
- Demo
> Add Prompt, Chunks in Create Key

- docs/pages/_app.mdx
> Update api key to new data

- application/requirements.txt
> fix: updated qdrant-client to v1.8.2

- application/api/user/routes.py
- application/parser/open_ai_func.py
- application/parser/remote/web_loader.py
- application/worker.py
> fix: remote upload error

- frontend/src/App.tsx
- frontend/src/Modal/index.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- frontend/src/preferences/DeleteConvModal.tsx
- frontend/src/settings/Documents.tsx
- frontend/src/settings/General.tsx
*  Closes #940 
* Fixes disoriented input field in UI
* Add dark mode to  Modal component and Delete confirmation
Enhances user experience User experience
> fix(UI):conversation,settings

- docs/pages/Deploying/Kubernetes-Deploying.md
- docs/pages/Deploying/_meta.json
- k8s/deployments/docsgpt-deploy.yaml
- k8s/deployments/mongo-deploy.yaml
- k8s/deployments/qdrant-deploy.yaml
- k8s/deployments/redis-deploy.yaml
- k8s/docsgpt-secrets.yaml
- k8s/services/docsgpt-service.yaml
- k8s/services/mongo-service.yaml
- k8s/services/qdrant-service.yaml
- k8s/services/redis-service.yaml
> feat: k8s deployment

- application/api/answer/routes.py
- application/core/settings.py
- application/retriever/brave_search.py
- application/retriever/classic_rag.py
- application/retriever/duckduck_search.py
- frontend/src/components/Dropdown.tsx
- frontend/src/conversation/conversationApi.ts
- frontend/src/conversation/conversationSlice.ts
- frontend/src/preferences/preferenceSlice.ts
- frontend/src/settings/General.tsx
- frontend/src/store.ts
> feat: dropdown to adjust conversational history limits

- docs/package-lock.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/Hero.tsx
- frontend/src/Navigation.tsx
- frontend/src/components/SourceDropdown.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/locale/en.json
- frontend/src/locale/es.json
- frontend/src/locale/i18n.ts
- frontend/src/modals/ConfirmationModal.tsx
- frontend/src/modals/DeleteConvModal.tsx
- frontend/src/modals/index.tsx
- frontend/src/settings/APIKeys.tsx
- frontend/src/settings/Documents.tsx
- frontend/src/settings/General.tsx
- frontend/src/settings/Prompts.tsx
- frontend/src/settings/index.tsx
- frontend/src/upload/Upload.tsx
* Added i18n support for multiple languages
* Support for Spanish *(es)* language
* In Settings > general, languages can be switched
Ease of use for diverse user base.
> Internationalisation with i18next

- docs/pages/index.mdx
> DocsGPT link update

- frontend/src/settings/Documents.tsx
> Denominations on tokens

- frontend/index.html
- frontend/src/Hero.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/index.css
- fixes issue where input field got behind url bar in Safari (iOS)
> fix: input field covered by url bar in safari

- frontend/src/locale/i18n.ts
- frontend/src/locale/zh.json
- frontend/src/settings/General.tsx
Adds in Mandarin translation into DocsGPT
https://github.com/arc53/DocsGPT/issues/986
> Adding in Mandarin translation into DocsGPT

- application/Dockerfile
> upgrade docker to 24.04

- frontend/src/components/Dropdown.tsx
- frontend/src/components/SourceDropdown.tsx
- frontend/src/conversation/Conversation.tsx
> fix: modals close on clicking outside

- frontend/src/conversation/Conversation.tsx
- frontend/src/index.css
> fix: input box improvements

- frontend/package-lock.json
- frontend/src/upload/Upload.tsx
- Bug Report: UX enhancement
- [https://github.com/arc53/DocsGPT/issues/1019#issue-2383516127](url)
> Ux Enhancement

- application/api/user/routes.py
- frontend/src/conversation/Conversation.tsx
- frontend/src/index.css
- resolves #1021 for auto-scroll to end
- resolves clearing of previous text after pasting
> fix: changed query box from div to textarea

- application/parser/file/html_parser.py
- application/requirements.txt
> Upgrade unstructured

- extensions/react-widget/package-lock.json
- extensions/react-widget/package.json
- extensions/react-widget/src/components/DocsGPTWidget.tsx
- extensions/react-widget/src/main.tsx
- extensions/react-widget/src/types/index.ts
* Size parameter in DocsGPTWidget can be 'small' or 'medium'.
* Flexibility on widget dimensions
> Extensions: Add size option to react-widget

- extensions/react-widget/package-lock.json
- extensions/react-widget/src/assets/message.svg
- extensions/react-widget/src/components/DocsGPTWidget.tsx
- extensions/react-widget/src/requests/streamingApi.ts
- extensions/react-widget/src/types/index.ts
* Option to change theme 'light' | 'dark'
* Option to update the floating button icon
* Option to change floating button background
* More flexibility for client applications to personalise the bot interface.
> Upgrading options in React widget

- docs/package-lock.json
- docs/package.json
- docs/pages/Extensions/react-widget.md
- docs/pages/_app.mdx
- extensions/react-widget/README.md
* Fixes minor syntactical typos in the docs
* Update react widget version in /docs
* Updated Readme in extensions/react-widget
* Update the new version changes in react-widget
> Update docs: minor fixes, version update

- application/api/answer/routes.py
- application/app.py
- application/celery_init.py
- application/core/logging_config.py
- application/parser/remote/crawler_loader.py
- application/parser/remote/sitemap_loader.py
- application/retriever/brave_search.py
- application/retriever/classic_rag.py
- application/retriever/duckduck_search.py
- application/usage.py
- application/utils.py
- application/worker.py
> feat: logging

- extensions/react-widget/package-lock.json
- extensions/react-widget/package.json
- extensions/react-widget/src/components/DocsGPTWidget.tsx
* Adding markdown-it, replacing snarkdown.
* Made minor fix in light theme
* Maintaining the package.
> Widget: Replaced deprecated dependency

- application/core/settings.py
- application/llm/openai.py
- docs/pages/Guides/How-to-use-different-LLM.mdx
> feat: added easy way to proxy

- frontend/package-lock.json
- frontend/package.json
- frontend/src/conversation/ConversationBubble.tsx
- Added max width for Question
- Removed Markdown for questions.
- Updated package json with chart.js(missing dependency)
- Fixing UI bugs : Large text prompts like code snippets broke the UI.
> Fix : overflow in queries

- docker-compose-local.yaml
- Bug fix related to issue #1137 
This change enhances FE development experience using Docker.
> fix(Docker): Integrate a bind mount in the local docker compose file

- frontend/src/App.tsx
- frontend/src/Hero.tsx
- frontend/src/Navigation.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- frontend/src/conversation/conversationSlice.ts
- frontend/src/index.css
- frontend/src/settings/index.tsx
1. UI adjustments on mobile devices
2. Restructured the components in Conversation
Responsiveness
> Fix UI for mobile devices

- mock-backend/package-lock.json
- mock-backend/package.json
*Bug fix*
The bot has automatically upgraded the `json-server` version to `1.0.0-beta.2` which can't be imported correctly.
Related to #1136
> fix(deps): downgrade json-server to v0.17.4

- application/api/answer/routes.py
- application/api/user/routes.py
- application/app.py
- application/extensions.py
- application/requirements.txt
- application/utils.py
- frontend/src/components/Dropdown.tsx
- frontend/src/modals/CreateAPIKeyModal.tsx
- frontend/src/settings/Analytics.tsx
- a feature update, refactoring the routes to ensure compliance with the OpenAPI specification using Flask-RestX
- to align routes with the OpenAPI specification, ensuring consistent API documentation and facilitating easier integration with client libraries and tools
> feature: OpenAPI specification compliant endpoints

- frontend/src/upload/Upload.tsx
Select the doc element which is not present in the intersection of the current source docs and the fetched source docs from the API
Selects the document just trained.
> Fix: Auto select newly trained document

- frontend/src/Navigation.tsx
Bug Fix
This change addresses #1208
This fix will let the user navigate back to same conversation smoother after navigating to settings and deleting the conversation will reset the page.
> fix: navigation and deletion issues in conversations

- HACKTOBERFEST.md
simple Documentation error in [Hacktober](https://github.com/arc53/DocsGPT/blob/main/HACKTOBERFEST.md) file
> Documentation error in "Hacktoberfest.md"

- frontend/src/Hero.tsx
- frontend/src/index.css
- frontend/src/settings/APIKeys.tsx
- frontend/src/settings/Documents.tsx
Bug fix related to #1220 
- **Other information:**  
- Applied new styling rules for `table-default` using Tailwind CSS utilities.
- Improved code readability and maintainability by centralizing table styles in `index.css`.
> Fix(1220): border styles

- README.md
- frontend/src/Navigation.tsx
- frontend/src/components/SourceDropdown.tsx
- frontend/src/conversation/ConversationTile.tsx
> Fix: Minimise sidebar on nav item click on Mobile

- frontend/src/conversation/ConversationTile.tsx
- (Bug fix)
- **Why was this change needed?** 
- Fixes #1256
> Fix: Menu position on conversation list scroll

- application/worker.py
> fix: file check

- frontend/src/conversation/ConversationBubble.tsx
- frontend/src/conversation/ConversationTile.tsx
- frontend/src/locale/en.json
- frontend/src/locale/es.json
- frontend/src/locale/jp.json
- frontend/src/locale/zh.json
Minor fix
closes: https://github.com/arc53/DocsGPT/issues/1261
> Remove Icon Next to Question Bubble and Label Change

- HACKTOBERFEST.md
- docs/pages/Guides/How-to-train-on-other-documentation.mdx
- docs/pages/Guides/How-to-use-different-LLM.mdx
docs update
A bit easier to read
Thanks for maintaining the library
> Fix some typos

- frontend/src/components/SettingsBar.tsx
Made the desired changes for better Ui/Ux
Fixes: #1285 
> 🚀 Feature: Tabs in settings redesign

- README.md
updates the current demo 
- previous one was outdated 
> DocsGPT DEMO UPDATED

- frontend/src/Navigation.tsx
- frontend/src/components/Help.tsx
- frontend/src/locale/en.json
- frontend/src/locale/es.json
- frontend/src/locale/jp.json
- frontend/src/locale/zh-TW.json
- frontend/src/locale/zh.json
* Matching the colour scheme, margins, padding as in figma
* Closes #1165
> Minor UI adjustments in Navigation > Help

- frontend/src/components/Help.tsx
> fix: help button margin

- frontend/src/Navigation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- **What kind of change does this PR introduce?** Bug Fix
- **Why was this change needed?** Fixes #1350 
> Fix like hovering state in dark mode

- extensions/discord/bot.py
> fix: slightly better discord bot formatting

- docs/theme.config.jsx
I added a Edit on GitHub button
By adding this feature, contributors can have an easier time make edits or find the page that needs the update before they make a Pull Request. 
Closes #1331 
This is my submission for Hacktoberfest
> feat: add edit buttons

- docs/package-lock.json
- docs/package.json
- extensions/react-widget/package-lock.json
- extensions/react-widget/package.json
Updates:
* Custom dimensions(width, height, maxHeight, maxWidth) in widget
* UI enhancement, CSS structuring
> React Widget update - v0.4.4

- docs/package-lock.json
- docs/package.json
- extensions/react-widget/package-lock.json
- extensions/react-widget/package.json
- extensions/react-widget/src/components/DocsGPTWidget.tsx
1. Avoiding effect of external CSS on the widget
Explicit styling
> React Widget: udpated to v0.4.5

- extensions/react-widget/src/components/DocsGPTWidget.tsx
- extensions/react-widget/src/types/index.ts
- Added animation on opening and closing the widget
- Changed the floating button design
- UX
> (feat: widget): smooth transitions

- docs/package.json
- extensions/react-widget/package-lock.json
- extensions/react-widget/package.json
- Adding smoother transitions
- Changing floating button design, new parameter `buttonText`.
- UX
> React Widget: published v0.4.6

- docs/package-lock.json
- docs/package.json
- extensions/react-widget/package-lock.json
- extensions/react-widget/package.json
New Updates:
1. Enhanced widget transition
2. Transition for modal pop-up
> React Widget v0.4.7

- frontend/src/upload/Upload.tsx
updates the color of the loader while training, and updates the size of the spinner
fixes: #1438 
> refactor: loader-color

- docs/package-lock.json
- docs/package.json
- docs/pages/Extensions/react-widget.md
- docs/pages/_app.mdx
- extensions/react-widget/README.md
- extensions/react-widget/package-lock.json
- extensions/react-widget/package.json
- extensions/react-widget/src/browser.tsx
- extensions/react-widget/src/components/SearchBar.tsx
- extensions/react-widget/src/index.ts
- extensions/react-widget/src/main.tsx
> React Widget: Updating to v0.4.8

- application/api/answer/routes.py
- frontend/src/Navigation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- frontend/src/conversation/conversationSlice.ts
- frontend/src/settings/Documents.tsx
1. Deletes following queries from the database
2. updates the state safely in the frontend.
3. Exacted to the UI design
4. Close the editable input when clicked outside or <kbd>ESC</kbd>
UX
> (fix:edit-query)delete following queries

- docs/package.json
- extensions/react-widget/package-lock.json
- extensions/react-widget/package.json
New Updates : Enhanced UI in SearchBar component mentioned in #1527
> Releasing docsgpt npm library v0.4.9

- extensions/react-widget/publish.sh
- extensions/react-widget/src/components/SearchBar.tsx
1. Center the Toolkit in the Search button
2. Fixes the publish.sh -  package json is not affected my publish. Only version should be updated
generally while publishing the targets were removed from the package json which may get committed and required a fix
> Widget fixes

- application/parser/remote/web_loader.py
Changes web loader to the correct output.
Bug fix
Fixes web loader.
> web loader fix

- docs/theme.config.jsx
documentation update, the footer now contains links
easier navigation
> footer text with links

- .github/workflows/ci.yml
- .github/workflows/cife.yml
- .github/workflows/docker-develop-build.yml
- .github/workflows/docker-develop-fe-build.yml
> Arm builds

- application/api/user/routes.py
- application/tools/agent.py
- application/utils.py
- frontend/src/modals/AddActionModal.tsx
- frontend/src/modals/AddToolModal.tsx
- frontend/src/modals/ChunkModal.tsx
- frontend/src/settings/Tools.tsx
> Handle bad tool names

- docs/pages/Extensions/chat-widget.mdx
- docs/pages/_app.mdx
Sync docs with docsgpt-react@0.4.11
> (feat:widget) udpate docs

- docs/package-lock.json
- docs/package.json
- extensions/react-widget/package-lock.json
- extensions/react-widget/package.json
- extensions/react-widget/publish.sh
- extensions/react-widget/src/components/DocsGPTWidget.tsx
Version release *v0.5.0*
* Fixes Feedback collection
* autoscrolling is simplified
#1647
> Widget upgrade to 0.5.0

- application/api/answer/routes.py
- application/cache.py
> Fixes cache

- setup.sh
> fix: docker compose up doesn't use the env 

- frontend/src/Hero.tsx
- frontend/src/components/Input.tsx
- frontend/src/components/MessageInput.tsx
- frontend/src/components/SourceDropdown.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationMessages.tsx
- frontend/src/conversation/SharedConversation.tsx
- frontend/src/conversation/conversationSlice.ts
- frontend/src/index.css
- frontend/src/modals/ShareConversationModal.tsx
- frontend/src/utils/dateTimeUtils.ts
* Refactored the `Conversation` and `SharedConversation` components by extracting reusable components for improved maintainability and reusability.
*  Extracted `ConversationMessages` component for handling message rendering.
* Extracted `MessageInput` component for handling input field and message sending.
* State management is still decoupled between both the components
*  Reduced code duplication.
* Improved modularity and reusability.
* Easier to maintain and extend in the future.
* added function to confirm before deleting docs from source dropdown
* aligment of Hero, Conversation and Textarea is …
> Refactor(fe): Conversation

- application/agents/llm_handler.py
- application/api/answer/routes.py
- application/api/user/routes.py
- application/cache.py
- application/llm/google_ai.py
- application/llm/openai.py
- application/logging.py
- application/parser/embedding_pipeline.py
- application/parser/remote/crawler_loader.py
- application/parser/remote/sitemap_loader.py
- application/parser/remote/web_loader.py
- application/retriever/classic_rag.py
- application/vectorstore/mongodb.py
- application/worker.py
> fix: enhance error logging with exception info across multiple modules

- frontend/src/agents/NewAgent.tsx
> fix: sources icon mini fix

- frontend/src/agents/index.tsx
> fix:(style) update layout for agent list and card components

- application/agents/classic_agent.py
- application/agents/react_agent.py
> fix: truncate tool call results to 50 characters for cleaner output

- application/api/user/routes.py
- frontend/src/agents/NewAgent.tsx
> refactor: handle empty sources and chunks in agent

- application/prompts/chat_combine_creative.txt
- application/prompts/chat_combine_default.txt
- application/prompts/chat_combine_strict.txt
> refactor: enhance AI assistant prompts for clarity and creativity

- application/llm/openai.py
- setup.sh
- fix for OpenAI trying to use base_url=""
- fix for ollama container error: `Error code: 404 - {'error': {'message': 'model "MODEL_NAME" not found, try pulling it first', 'type': 'api_error', 'param': None, 'code': None}}`
> fix for OPENAI_BASE_URL + ollama can't connect to container

- extensions/react-widget/src/components/SearchBar.tsx
- relying on custom color schemes that maintains contrast for readability and gives a sleek glassmorphic appearance to the search widget
UI
> Glassmorphic effect on search widget

- application/agents/react_agent.py
- application/prompts/react_planning_prompt.txt
> React improve

- application/api/user/routes.py
- application/utils.py
- frontend/package-lock.json
- frontend/package.json
- frontend/src/agents/AgentPreview.tsx
- frontend/src/agents/NewAgent.tsx
> feat: improve interactivity of publishing/drafting of agents

- application/api/user/routes.py
- application/core/settings.py
- application/parser/file/image_parser.py
- application/vectorstore/pgvector.py
- application/vectorstore/vector_creator.py
> feat: implement PGVectorStore for PostgreSQL vector storage

- application/agents/base.py
- application/api/answer/routes/answer.py
- application/api/answer/routes/base.py
- application/api/answer/services/stream_processor.py
- application/api/user/routes.py
- application/llm/base.py
- application/llm/google_ai.py
- application/llm/openai.py
- frontend/src/agents/NewAgent.tsx
- frontend/src/agents/agentPreviewSlice.ts
- frontend/src/agents/types/index.ts
- frontend/src/conversation/conversationModels.ts
- frontend/src/conversation/conversationSlice.ts
- Enhanced AnswerResource to handle structured responses and integrate structured_info into the response.
- Updated BaseAnswerResource to generate structured output based on JSON schema and log structured output details.
- Modified StreamProcessor to include json_schema in processing.
- Extended user routes to support json_schema in agent creation and updates, including validation for JSON schema format.
- Implemented structured output support in BaseLLM and its subclasses (GoogleLLM, OpenAILLM) with methods for preparing structured output formats.
- Updated frontend components to manage JSON schema input, validation, and integration with agent creation and editing workflows.
- Enhanced agent preview and conversation models to accommodate structured response handling.
> feat: add support for structured output and JSON schema validation

- tests/test_app.py
Fixes `FAILED tests/test_app.py::test_app_config - AttributeError: module 'application.api.answer.routes.answer' has no attribute 'register'`
> Test app fix

- application/agents/base.py
- application/retriever/classic_rag.py
> fix: chunking

- tests/parser/file/test_docs_parser.py
- tests/parser/file/test_epub_parser.py
- tests/parser/file/test_html_parser.py
- tests/parser/file/test_image_parser.py
- tests/parser/file/test_json_parser.py
- tests/parser/file/test_markdown_parser.py
- tests/parser/file/test_pptx_parser.py
- tests/parser/file/test_rst_parser.py
- tests/parser/file/test_tabular_parser.py
- tests/parser/remote/test_crawler_loader.py
- tests/parser/remote/test_crawler_markdown.py
- tests/parser/remote/test_github_loader.py
- tests/parser/remote/test_reddit_loader.py
- tests/parser/remote/test_web_loader.py
Tests for appication/parsers/file/* (bulk.py usage) and the application/parsers/remote
maintainability, SDLC
> Test coverage for parsers

- application/api/answer/routes/base.py
> fix: api answer tool call event

- application/core/settings.py
- application/tts/elevenlabs.py
- tests/security/test_encryption.py
- tests/storage/test_local_storage.py
- tests/storage/test_s3_storage.py
- tests/tts/test_elevenlabs_tts.py
- tests/tts/test_google_tts.py
* Comprehensive test suites for both S3Storage and LocalStorage implementations with properly isolated third-party dependencies.
* Tests for `application/security/encryption.py`
* Tests for `application/tts/*` 
* Additional change: reverted the `application/tts/elevenlabs.py` to the cloud version
SDLC
```
=========================================== tests coverage ===========================================
__________________________ coverage: platform linux, python 3.12.3-final-0 ___________________________
Coverage XML written to file coverage.xml
================================== 244 passed, 6 …
```
> Test coverage:  TTS, Security and Storage layers

- frontend/src/App.tsx
- frontend/src/Navigation.tsx
- frontend/src/agents/AgentLogs.tsx
- frontend/src/agents/NewAgent.tsx
- frontend/src/agents/index.tsx
- frontend/src/components/CopyButton.tsx
UI Enhancements
https://github.com/arc53/DocsGPT/issues/1993
> Feat: UI enhancements
