- application/templates/index.html
Remove the odd " >" in the href
> Fix the langchain URL

- README.md
- extensions/chrome/popup.js
> docs: fix typos

- scripts/parser/open_ai_func.py
I don't know why there needs to be a `store.index = None`, but I got an error when continuing the process, so I restored the index before continuing;
But that's only fixed the index issue.
Another problem is there is no error catch for the `store.add_texts([i.page_content], metadatas=[i.metadata])` in the `except` block, so if 10 seconds is not enough (maybe set it to 60?), then the second error will be thrown out, and this time, no `try/except` for this one
> fix: restore index back when continue process

- scripts/ingest.py
- scripts/parser/open_ai_func.py
example: `python ingest.py --dir inputs1 --dir another --dir ../inputs`, 
the outputs will be in `outputs/input_folder_name/`,
also:
- fix the `-y` option,
- rename `--files` to `--file`
- rename `--directory` to `--dir`
what's more: may need to update docs or wiki
> feat: add support for directory list

- application/requirements.txt
- scripts/parser/open_ai_func.py
* Add a retry policy to increase stability when calling OpenAI API.
* This PR is a workaround for #55 , as explained here: https://github.com/arc53/DocsGPT/issues/90#issuecomment-1430688573
* This PR closes: #90
> Add retry strategy to increase stability

- .gitignore
- application/app.py
- application/error.py
- application/static/src/chat.js
- application/templates/index.html
> Fix the servor 500 error and show error message to client

- frontend/.env.development
- frontend/.env.production
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- frontend/src/conversation/conversationApi.ts
- frontend/src/conversation/conversationModels.ts
- frontend/src/conversation/conversationSlice.ts
1] Changes the conversation model from single Message type to Query which would contain prompt and its response.
2] Adds an API request to send feeback.
3] Adds env files
> Refactors singular Message model to Query model & adds api request to post feedbacks

- frontend/src/Navigation.tsx
- frontend/src/conversation/ConversationBubble.tsx
this pr focus on two tasks mentioned in the Roadmap:
1. Set all paddings of the text in messages to 0.9rem (on mobile too)
2. The arrow in the documentation selection dropdown should look down when closed (up if opened)
related: https://github.com/arc53/DocsGPT/issues/157
> feat: ui enhancement

- .env-template
- application/app.py
- application/core/settings.py
- application/worker.py
I started considering implementing some unit tests but decided to refactor env variable usage. 
Pydantic settings model allows storing all global variables in one place, simplifying their usage and easily overriding them in the future.
> Moved env variables to the pydantic settings file 

- README.md
- application/Dockerfile
- application/requirements.txt
- docker-compose.yaml
I wanted to play around with the code, but it was a bit struggle for me, so I'd like to contribute my findings.
As wrote in discord, I had a problem on a debian fresh install with `pip install -r application/requirements.txt`, I get error:
```
subprocess.CalledProcessError: Command '['./build_bundled.sh', '0.1.97']' returned non-zero exit status 127.
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for sentencepiece
Running setup.py clean for sentencepiece
```
When I remove the sentencepiece specific version (==0.1.97), pip figures it out and can install all packages without an issue. Is there a reason you have hardcoded version numbers? I did not change this tho. But I'm interested why do I have this …
> Improve dev setup docs

- .github/workflows/ci.yml
Avoid unnecessary and failing GHA build runs on forks.
> prevent this action from running on forks as it fails anyway.

- application/.env_sample
- application/Dockerfile
- application/app.py
- application/core/settings.py
- application/wsgi.py
- docker-compose-azure.yaml
- docker-compose.yaml
- extensions/chrome/popup.js
- extensions/discord/bot.py
- extensions/web-widget/src/js/script.js
- frontend/.env.development
- frontend/src/conversation/conversationApi.ts
- scripts/parser/file/markdown_parser.py
- setup.sh
Hey, there was a bug when you sent more than a few messages, the content would just get too long for a GET request, and the ui just got stuck.
I changed the stream method to POST.
There was another bug I fixed when tried to use the documentation embedding indexing.
Also, changed the port to a less used one as I had port conflicts.
> Fixed bugs, changed backend port

- README.md
I noticed missing information about the project stack (about React and Vite that I saw in other parts of the documentation), as well as some simple readability changes for the install instructions. 
(I'm planning to contribute with code too but I saw these during my research.)
> Added some missing info on the Readme

- frontend/src/Modal/index.tsx
- frontend/src/preferences/APIKeyModal.tsx
- frontend/src/preferences/SelectDocsModal.tsx
This PR extracts out the Modal functionality into a generic Modal component onto which actual views are rendered through render props.
---
[Both of the existing modal components](https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0%3A1&t=Xqi6tyl2G3mghdiP-0) have few things in common:
1]They both overlay over existing page. Both have similar CSS design(rounded corners, shadows).
2]Both have some similar functions as well, both will go away when "save" is clicked. As for now one of them have cancellation feature but as we add more modals, this too can be a common functionality.
These things should be moved to a generic component. This modal will accept :
1]save click handler as a prop
2]isCancellable boolean prop to decide whether to enable the cancellable feature or not. …
> feat: use generic Modal with render props

- application/parser/token_func.py
- scripts/parser/token_func.py
documents with (length >= min_tokens) should not be grouped into one document for indexing.
> Fix min_tokens logic for grouping documents

- .github/workflows/pytest.yml
- CONTRIBUTING.md
This PR is only about documentation change, please review.
> Adapt documentation to existing tests.

- frontend/src/assets/arrow-down.svg
- frontend/src/conversation/Conversation.tsx
This will show the scroll to bottom button when user scrolls to top from the last message.
Closes #170
> feat(ui): add scroll to bottom button

- README.md
Fixes #347 I have fixed the links of some of the GitHub badges which were previously linking to Discord
> Fixed GihHub badges in README.md links

- HACKTOBERFEST.md
- application/vectorstore/elasticsearch.py
- setup.sh
Fixes some spelling
To standardize the docs and spelling.
> misc: fix spelling

- tests/llm/test_openai.py
- tests/test_error.py
Removes old code comments
Removes hard coded file paths which are not needed
> tests(python): remove unneeded comments

- docs/pages/Deploying/Hosting-the-app.md
There were a lot of grammatical errors and typos that I fixed to improve the readability of the document.
> [DOCS] Update Hosting-the-app.md

- frontend/src/conversation/Conversation.tsx
Issue ID #382
The Input Field now handles Empty Spaces
> Fixed Empty Spaces Passed in the Input Field

- frontend/src/conversation/ConversationBubble.tsx
- **What kind of change does this PR introduce?** (Bug fix)
#426 
- By giving a style of **"break-all"** to add line breaks whenever necessary, without trying to preserve whole words.
Before
After
> Fixed Overflowing Text messages with long strings without spaces

- frontend/src/conversation/Conversation.tsx
- frontend/src/index.css
This PR aims to add a placeholder in the search div using css attributes
#422 
The search div before changes 
After changes
https://github.com/arc53/DocsGPT/assets/85943021/0c069f64-2eac-4662-b8d0-8e80e4e4abf3
> Added css attribute placeholder for search div

- frontend/public/lock.svg
- frontend/public/message-programming.svg
- frontend/public/message-text.svg
- frontend/src/Hero.tsx
- frontend/src/conversation/Conversation.tsx
I have resolved the scripts folder and the card one kindly check and merge under hacktoberfest thank you :)
@dartpain 
> fixed homepage

- frontend/src/Navigation.tsx
Bug Fix- Close #452 
- **Why was this change needed?** 
- Actually, when you select the source file from the dropdown, It affects the UI, if, the source file name is large. 
**Before Fix:** 
**After Fix:**
> [Fix] Source selection overflow issue 

- application/core/settings.py
- application/llm/sagemaker.py
- tests/llm/test_sagemaker.py
Adds proper sagemaker endpoint handling with respone streaming
It allows to stream responses now
> sagemaker streaming

- application/vectorstore/faiss.py
> Fix faiss import bug

- frontend/src/Navigation.tsx
Fixed: Tabs overlapping due to text overflow by limiting the text length.
[Tabs overlap issue](https://github.com/arc53/DocsGPT/issues/444)
- before :
-after :
> Fix: Conversations tabs overlapping

- frontend/src/conversation/conversationSlice.ts
This PR introduces a new feature to the Conversation module that allows users to provide feedback on answers generated by the chatbot. Users can now like or dislike responses, helping to improve the quality of answers provided.
This change was needed to enhance the user interaction with the chatbot. Feedback from users can help improve the accuracy and relevance of responses over time. Additionally, this feature aligns with user expectations for modern chatbot experiences.
-     The /conversation folder has been updated to include the following enhancements:
- Users can provide feedback (LIKE/DISLIKE) on …
> Add Feedback Feature to Conversation Module (Update conversationSlice.ts)

- frontend/src/Navigation.tsx
> Fix About page to Conversation navigation

- README.md
- **What kind of change does this PR introduce?**   -  Docs Update
- **Why was this change needed?** - Adding both activation commands (venv/Scripts/activate and . venv/bin/activate) is necessary to accommodate users on different operating systems (Windows, Unix-based) and provide clear, error-free instructions in the Readme markdown file.
I initially attempted to use the default command . venv/bin/activate, but it didn't work for me. This prompted me to include the alternative venv/Scripts/activate command in the README for Windows users like me.
> Krishvsoni patch 1

- frontend/src/App.tsx
- **What kind of change does this PR introduce?**
This very small PR fixes a bug for the wrong left margin on the content container which was not in line with the sidebar width.
- **Why was this change needed?**
Part of the content was hidden behind the sidebar on certain viewport sizes.
| Before | After |
|--------|-------|
|![docsgpt arc53 com](https://github.com/arc53/DocsGPT/assets/15653065/7547dedb-ba82-423f-b97f-2e3cc8704d2f) | ![docsgpt arc53 com (1)](https://github.com/arc53/DocsGPT/assets/15653065/a7b570bb-2fe4-466b-806f-c7c7b528b413) |
> Fix: adjust left margin on content container

- frontend/src/conversation/ConversationBubble.tsx
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...) 
-  Bug Fix
-  The message box just need to little tailwind, I gave it a width. So, now it does not overflow
- https://github.com/arc53/DocsGPT/issues/410
-  Thanks for the opportunity. Do tell me If any feedback or change is needed.
> bug(front): The text seems to go out of screen when the result is too big.

- application/worker.py
- scripts/ingest.py
Overview
This pull request introduces changes to the backend code to enhance its readability, maintainability, and scalability.
Changes:
1. Simplified Conditional for API Call
Reduced redundant conditions for determining when to call the OpenAI API.
2. Concise String Manipulation
Optimized the string manipulation method for joining parts of a title.
3. Scalable Code for Language Support
Introduced a dictionary-based approach for language support, making it more scalable. This ensures that new languages can be added in the future with minimal changes, as opposed to multiple conditional statements.
Conclusion:
These backend modifications aim to make the codebase more intuitive and future-proof. Feedback is appreciated.
> Backend Code Refactoring for Better Readability and Scalability

- frontend/src/conversation/Conversation.tsx
Updated the user conversation input field with autofocus feature
This update enhances user experience as most modern chat fields have this feature. Users can directly start typing once the page has loaded
Before the update (Screenshot):
After the update (Screenshot):
> UI update - Added autofocus for user chat input 

- frontend/src/Navigation.tsx
- frontend/src/conversation/ConversationTile.tsx
Fix the font size and alignment of all the chat options of the sidebar based on issue #586
> Fix the font size and alignment of all the chat options of the sidebar based on issue #586

- frontend/src/upload/Upload.tsx
- It solved issue #539 
- Before File Selection:
I introduced two changes in it i added a red asterisk denoting user must choose file in order to enable train button as no file is selected above it's disabled above
After File Selection:
After selecting some file the Train button will be enabled and pointer will be cursor on it 
This change is needed because if a user trains without giving any file then the website is staying idle in uploading state 
> Train button Disabled Before Selecting File

- frontend/src/Navigation.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationTile.tsx
JSX conditional rendering can be simplified to use the logical AND operator (`&&`) [^1] instead of ternary operator (`? :`) if we want to render something only when the conditon is true, and nothing otherwise.
[^1]: https://react.dev/learn/conditional-rendering#logical-and-operator-
> refactor(frontend): simplify JSX conditional rendering

- frontend/src/Navigation.tsx
Resolved: #582
Fixed the sidebar toggling glitch transition on desktop
Issue: #582
before:
After:
> sidebar glitch fixed

- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
-  **Bug Fix**
- Issue: #533 
- Remove the extra (leading) spaces from the response
- Added ```const trimmedResponse = query.response.trim();``` to trim the response
- Return the trimmed response if ```trimmedResponse.length > 0```, else ```No answer found.```
<br>
- **Conversation.tsx** (frontend/src/conversation/Conversation.tsx)
<br>
> fix: Remove extra spaces in response

- application/requirements.txt
- application/vectorstore/faiss.py
- tests/test_vector_store.py
I want this PR to address this issue: https://github.com/arc53/DocsGPT/issues/550 and raise a more legible error if the embeddings have a different length of `word_embedding_dimension` than the `docsearch.index` dimension.
It's needed because not checking the different vector embedding lengths can lead to unexpected and unwanted behaviour.
The initial solution I have for this is pretty ugly so I welcome a discussion in order to find the best solution and hopefully fix the more general problem of word embedding dimension checking for all models.
> raise more legible error if the word embedding dimensions don't match

- frontend/src/conversation/ConversationBubble.tsx
Prevent unnecessary renders. Update show/hide state of feedback buttons by css instead React
Update show/hide state by CSS much faster than working through React
> [FE]Prevent unneccessary renders. 

- frontend/src/Navigation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- frontend/src/upload/Upload.tsx
This PR fixes #618 
Changes the `frontend/src/Navigation.tsx` component's `z-index`. 
This was needed because the content that should be below the header was flowing over it in small screens. See below:
> Fix(frontend):  fix Navigation component z-index for small devices

- frontend/src/About.tsx
Bug fix - The about-section was not properly aligned in the center on the About page.
> [Bug]:About section not Aligned.

- frontend/src/About.tsx
Bug Fixed : I have aligned about-section (on the about page) in the center as per Figma design.
Fixed an bug #645
- **It is properly aligned in the center, as shown below**:
> I have aligned about page in the center.

- frontend/src/hooks/index.ts
Feature
- **useOutsideAlerter:** This change was needed to enhance the useOutsideAlerter hook by adding the ability to handle clicks outside a specified ref element and optionally handle the 'Escape' key press. This addition allows for more robust handling of click events in various components, such as modals and popovers.
- **useMediaQuery:** The change was also necessary to expand the useMediaQuery hook's functionality. It now includes the detection of dark mode using the prefers-color-scheme: dark media query. This update provides a more comprehensive way to adapt UI elements to the user's system-wide preferences.
- **Other …
>  Enhanced Hooks with Outside Click Handling and Dark Mode Detection

- frontend/tailwind.config.cjs
- **What kind of change does this PR introduce?**
**Enhancing**, backdrop color effect in when _trigger upload new document modal_ and _trigger upgrade modal_ both using tailwind utility class named `gray-alpha` enhanced the opacity from `.1` to `.64`
**Design Consistency**, refer to when _trigger sign up or sign in modal_ their backdrop color is darker than other modals (the difference is in the opacity value)
> Enhance backdrop modal effect

- docs/pages/Guides/How-to-use-different-LLM.md
> Enhanced How-to-use-different-LLM.md

- README.md
Fixes a typo in the Quickstart Guide.
OPENAI_API_KEY wouldn't help the application start instead naming the variable API_KEY works.
> docs: Typo in quickstart guide fixed

- frontend/src/Hero.tsx
This PR fixes the bug on the hero component, which was not behaving as expected on different devices.
The change was requested in issue #581 
Here are some *screenshots* that can help in understanding the changes I have made.
> fix: Hero section styling fixed, made responsive across all devices

- README.md
Add accessibility features to README file based on the top tips from GitHub: https://github.blog/2023-10-26-5-tips-for-making-your-github-profile-page-accessible/
Add accessibility features to README file based on the top tips from GitHub: https://github.blog/2023-10-26-5-tips-for-making-your-github-profile-page-accessible/
The README on your GitHub profile acts like a front door to your work, skills, and professional self, so it’s important that everyone who visits your profile can read and understand it.
> Make README accessible

- frontend/src/conversation/Conversation.tsx
In this PR, I make the the background color accessible based on the following advice from the Accessible Insights website:
Fix the following:
- Element has insufficient color contrast of 3.94 (foreground color: #808080, background color: #ffffff, font size: 9.0pt (12px), font weight: normal). Expected contrast ratio of 4.5:1Element has insufficient color contrast of 3.94 (foreground color: #808080, background color: #ffffff, font size: 9.0pt (12px), font weight: normal). Expected contrast ratio of 4.5:1
- Use foreground color: #727272 and the original background color: #ffffff to meet a contrast ratio of 4.81:1.
This change …
> feat: made color accessible

- CONTRIBUTING.md
Documentation update/fix.
I see that `DocsGPT` is using `main` as it's primary branch and not `master` but in the `CONTRIBUTING` guide you are mentioning:
```
git pull upstream master
```
So, it should be changed to the following for better clarity.
```
git pull upstream main
```
> Fixed branch name from `master` to `main` in the contributing guide.

- codecov.yml
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, …)
Fixed wrong closing parenthesis in `codecov.yml`
The `codecov.yml` file will not work as intended because the closing parenthesis are wrong.
> Fixed wrong closing parenthesis in `codecov.yml`

- application/core/settings.py
- docs/pages/Developing/API-docs.md
- frontend/src/Hero.tsx
- frontend/src/index.css
- This PR introduces a new **feature** to improve the **mobile responsiveness** of the website. 
- **Why was this change needed?** 
- Fixes issue #682 
- Previously, users had to **scroll down** on **mobile** devices to access the input field on the _home page_. This change enhances the user experience by ensuring that the input field is immediately visible, eliminating the need for unnecessary scrolling.
- _Before:_
- _After:_
> Feat: enhance mobile responsiveness of Hero Page final

- frontend/package-lock.json
- frontend/package.json
- frontend/src/conversation/ConversationBubble.tsx
Feature: Render markdown tables in conversation
Issue - https://github.com/arc53/DocsGPT/issues/634
> Render tables in conversation

- frontend/src/Setting.tsx
- UI ->
- fixes #664 
-  I've created the complete UI in Typescript only, here's the preview of the UI
[Preview](https://github.com/arc53/DocsGPT/assets/74039834/87d8400b-b211-4f8a-8ca6-ea70a700a2d1)
@tenokami @dartpain
> [Code]:Setting Section UI

- docs/pages/Deploying/_meta.json
- Docs Fix/Update
There was a typo that needed to be corrected.
This PR changes `Rainway` to the correct spelling `Railway`.
> Corrected Typo on _meta.json

- application/api/answer/routes.py
> fix path bug on default

- docker-compose-mock.yaml
- mock-backend/Dockerfile
- mock-backend/package-lock.json
- mock-backend/package.json
- mock-backend/src/mocks/db.json
- mock-backend/src/mocks/routes.json
- mock-backend/src/server.js
Mock backend server
https://github.com/arc53/DocsGPT/issues/391
> Mock backend server

- application/requirements.txt
Fix 'mistral' models missing
It fixes Bug mentioned in Issue #800. It upgrades the HF Transformers library.
All models based on Mistral do not work. After this upgrade of the HF Transformers library they get running.
Tests are well passed:
=============================== test session starts ===============================
platform linux -- Python 3.10.10, pytest-7.3.1, pluggy-1.3.0
rootdir: /VSCode/DocsGPT
plugins: anyio-3.7.1
collected 20 items                                                                
tests/test_app.py .                                                         [  5%] …
> Update requirements.txt HF Transformers

- frontend/src/Navigation.tsx
There was repetitive alt text for the icons/links on the website. So I gave them more descriptive names.
According to [Deque University](https://dequeuniversity.com/rules/axe/4.7/image-redundant-alt), repetitive alt text can confuse screen readers, thus, making it difficult for users with disabilities to navigate this project's website.
Closes #808
> fix: Making alt text less redundant

- application/vectorstore/document_class.py
- application/vectorstore/elasticsearch.py
- application/vectorstore/mongodb.py
- application/vectorstore/vector_creator.py
- tests/llm/test_openai.py
> Mongodb integration as vectorstore

- frontend/src/Hero.tsx
Fixes unwanted dimensional variation in different browsers(**Chrome, Firefox** web page looks a bit different)
The Hero component varies in dimensions in different browsers
> fix distortion on different browsers

- frontend/src/upload/Upload.tsx
- **What kind of change does this PR introduce?** (Bug Fix)
- **Why was this change needed?** (#809)
- The Train button will be disabled if the Document File Name is Empty. The Discussion is done in the Discord
> Fixed Empty Document Name Upload

- frontend/src/App.tsx
- frontend/src/Hero.tsx
- frontend/src/Navigation.tsx
- frontend/src/Setting.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationTile.tsx
- frontend/src/hooks/index.ts
* Fixes bug in the nav bar icons
* Adding Custom Hook ```useDarkTheme()``` which returns as ```[isDarkTheme, toggleTheme]```
* Appropriate icons didn't display as per the selected theme.
- **Demo**:
> Fix: Sidebar Icons update on changing theme

- frontend/src/Setting.tsx
- frontend/src/conversation/Conversation.tsx
* Fixes improper button removal after deletion of documents in settings.
* Reused the reducer to setSourceDocs() ensuring proper deletion of complete row from the UI.
* Fixes Input box in the Conversation, making it absolute with respect to the conversation bubbles.
* fixes #834
* Enhances responsiveness .
> Makes input field absolute in Conversation, fixes delete icon in Settings/Documents

- mock-backend/src/server.js
* Adding mock endpoints for `/api/get_single_prompt` and ```/api/get_prompts```
* Ease of testing the Frontend with the Mock server.
> (mock) adding prompt routes

- application/core/settings.py
- application/requirements.txt
- application/vectorstore/qdrant.py
- application/vectorstore/vector_creator.py
This PR intends to add support for Qdrant - https://qdrant.tech/ to be used as a vectorstore in DocsGPT.
You can try this out by setting the `QDRANT_LOCATION` value to `":memory:"` to use an in-memory instance for prototyping.
For using Qdrant server, run
```console
docker run -p 6333:6333 qdrant/qdrant
```
and set `QDRANT_LOCATION` to `"http://host:6333"`
> feat: Qdrant vectorstore support

- extensions/react-widget/src/components/DocsGPTWidget.tsx
UI Fixes and enhancement
* Alignment of message icon
* Font Size slightly increased
* Border radius of the widget component increased to 0.75rem 
* send button dimensions enhanced
* indented the prompt input field 
* cross(x) icon enlarged
Fixes #871 
- **Other Information**
> Widget UI fixes

- docs/package.json
- docs/pages/Extensions/react-widget.md
- extensions/react-widget/package.json
- extensions/react-widget/src/components/DocsGPTWidget.tsx
- extensions/react-widget/src/index.html
- Provides new user guidelines for the updated version of widget.
- Quick start to DocGPT npm lbrary.
> Docs Update

- docs/package.json
- extensions/react-widget/package-lock.json
- extensions/react-widget/package.json
- extensions/react-widget/src/components/DocsGPTWidget.tsx
- extensions/react-widget/src/requests/streamingApi.ts
- frontend/src/App.tsx
- frontend/src/Hero.tsx
- frontend/src/Navigation.tsx
- frontend/src/conversation/Conversation.tsx
- Pause Auto Scrolling on User events 
- Auto-Scroll will not continue on user mouse wheel event or moves tap(touch screen devices).
- Fixed errors during pre-commit hooks - ```lint-fix```.
- Introducing Markdown support for widgets using `snarkdown` to parse Markdown to HTML, using styled components `GlobalStyles` component to inject custom styling in the response.
- Enhance user experience and engagement.
- Formatting responses.
> Pause Auto-scroll on user interrupt

- .gitignore
- application/parser/remote/reddit_loader.py
- application/parser/remote/remote_creator.py
- application/worker.py
- frontend/src/components/Dropdown.tsx
- frontend/src/upload/Upload.tsx
Added the reddit loader from langchain (https://python.langchain.com/docs/integrations/document_loaders/reddit), as a 
remote loader
> Added reddit loader

- application/api/answer/routes.py
- frontend/src/components/SourceDropdown.tsx
- frontend/src/conversation/conversationApi.ts
This PR (ref #887 ) introduces a new feature that changes the default document selection to "Empty" and ensures that when no document is selected, chunks processed per query are set to 0. 
Currently default document has DocsGPT documentation which was confusing.
> added feature #887

- docs/pages/Developing/API-docs.md
- docs/pages/Extensions/_meta.json
- docs/pages/Extensions/api-key-guide.md
A guide about api keys to documentation
A new feature was introduced with API keys, so a guide would be nice
> API keys guide

- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- Fixes arbitrary word breaks, word break changed to normal, also added `leading-normal` for line height. 
- Fixes abnormal overflow behaviour - the input box and conversation are wrapped into one div container with column-aligned flex with heights divided in `vh`  also making the overflow scrolling in independent of input box with this change. 
- Fixes overflows in sources
- Hides text under input box
Fixes #923 
Makes UI more comfortable to use especially in mobile devices.
> Fix: Abnormal overflow on mobile screens and arbitrary word breaks.

- application/api/answer/routes.py
Fixes #938 
Overrides default chunks and prompt_id value with data retrieved from api_key
Makes `/stream`, `/api/search`, `/api/answer` requests more relevant with api_key passed in request body.
> FIx: API Key Parsing

- frontend/.env.development
- frontend/src/Hero.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/settings/Documents.tsx
Updated Hero.tsx according to the latest UI design, increased height of input field in conversation.
Sleek user interface.
> Updating Hero

- frontend/src/components/CopyButton.tsx
- frontend/src/conversation/ConversationBubble.tsx
> Feat : add copy button on code snippet

- application/api/internal/routes.py
- application/api/user/routes.py
- application/parser/open_ai_func.py
- application/worker.py
- frontend/src/models/misc.ts
- frontend/src/settings/Documents.tsx
* Closes #947 
* Calculates token count for document and remote workers.
* Appends token count in GET /api/combine as
```
[
{
"date": "24/05/2024 20:25:12",
"description": "Demo",
"docLink": "/home/manish/Documents/workplace/docsgpt/application/indexes/local/LLM",
"fullName": "Demo,
"language": "LLM",
"location": "local",
"model": "huggingface_sentence-transformers/all-mpnet-base-v2",
"name": "Demo",
"tokens": "0",
"version": ""
}, .... 
]
```
* Frontend : Shows token usage column for private vectors in Settings > Documents.
* Frontend: Updates Doc type in misc.ts : optional key tokens
* More transparency in terms of tokens …
> Feature: Token count for vectors

- frontend/src/conversation/conversationSlice.ts
When asking a question, the LLM's response streams in as it should, then disappears from the conversation once it is finished. It reappears if the page is refreshed.
The bug seems to occur when the token sent by the LLM is an empty string. In llama-cpp, the last token seems to always be an empty string. This causes the frontend to recognize the string as empty in conversationSlice.ts#L151, which in turn causes the code to enter the else part of the statement, which returns an empty response.
Fixes https://github.com/arc53/DocsGPT/issues/944
> Fix empty response in the conversation

- frontend/src/locale/en.json
- frontend/src/locale/es.json
- frontend/src/settings/General.tsx
Updates the locale dictionary. 
Sync translations with new changes.
> Fix: added translation for the conversation history dropdown

- frontend/src/locale/en.json
- frontend/src/locale/i18n.ts
- frontend/src/locale/jp.json
- frontend/src/settings/General.tsx
Made a japanese translation of en.json. Some words checked by a japanese person. I used `?` instead of the japanese character `？`.
Also corrected some spelling misstakes in en.json.
> my-japanese-translation

- docs/pages/Extensions/react-widget.md
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...) I have added the HTML Installation code for the "Setting up the DocsGPT Widget in Your React Project" page:.
Page required update to include html installation instruction.
- **Other information**: Link for issue: https://github.com/arc53/DocsGPT/issues/983
> Updated nextra docs with new html code block installation instruction

- application/api/answer/routes.py
- application/api/user/routes.py
- frontend/src/conversation/conversationSlice.ts
* Handles exceptions in stream route; Closes #910 
* Considering following cases:
1. If API key is invalid, or not found return status code 401, raise  ` Exception("Invalid API Key, please generate new key", 401)`
2. In case invalid parameters are passed through request body from Frontend, except for ValueError and stream `Malformed request body`
3. If the upstream LLM server fails to generate response, or the request fails from the server side, stream `Please try again later. We apologize for any inconvenience.`
4. If the frontend fails to send the request possibly because of Connection or Network issues, the extraReducer message is updated to `Something went wrong. Please check your internet …
> Better Error handling on /stream endpoint

- application/llm/llama_cpp.py
> fix: use singleton in llama_cpp

- frontend/package-lock.json
- frontend/package.json
- frontend/src/upload/Upload.tsx
Fixes errors produced on pre-commit `npm run lint`
```
96:42 error 'progress.percentage' is missing in props validation react/prop-types
125:22 error 'progress.percentage' is missing in props validation react/prop-types
128:65 error 'progress.taskId' is missing in props validation react/prop-types
190:34 error 'progress.percentage' is missing in props validation react/prop-types
191:29 error 'progress.failed' is missing in props validation react/prop-types
257:40 warning 'isDragActive' is assigned a value but never used @typescript-eslint/no-unused-vars
291:17 error 'progress.type' is missing in props validation react/prop-types
293:24 error 'progress.type' is missing in props validation …
```
> Fix: Lint, props validation error

- frontend/package.json
- frontend/src/locale/i18n.ts
feature: on first visit, user's browser language is detected and used if supported. Otherwise, English is used.
Users no longer have to set their primary language manually in the app.
closes: https://github.com/arc53/DocsGPT/issues/1016
> FEAT: Auto Language Detection using User's Browser Default

- frontend/src/conversation/ConversationBubble.tsx
This PR is being made to implement the below feature
[https://github.com/arc53/DocsGPT/issues/1020](https://github.com/arc53/DocsGPT/issues/1020)
Implementing the following feature  [https://github.com/arc53/DocsGPT/issues/1020](https://github.com/arc53/DocsGPT/issues/1020)
Nope
> Feat implementation / #1020

- application/Dockerfile
Optimization of Dockerfile to reduce image size and improve build efficiency.
This change aims to reduce Docker image size and enhance build efficiency. By merging apt-related RUN commands, we consolidate cleanup operations within the same layer, effectively reducing image size. Additionally, we removed the redundant apt-get clean command, as this operation is automatically handled in the Ubuntu base image.
The reason why to remove `apt-get clean` is based on Docker's official best practices guide. More details can be found at:
- https://docs.docker.com/build/building/best-practices/#apt-get
These …
> Optimize Dockerfile to reduce image size and improve build efficiency

- extensions/react-widget/src/main.tsx
* Fixes, window is not defined error
* Renders window conditionally only if the typeof window is not undefined, the use of windows may cause conflict in server side.
* Compatibility with web frameworks
> React Widget: Fix for Next.js

- extensions/react-widget/package.json
- extensions/react-widget/src/components/DocsGPTWidget.tsx
- extensions/react-widget/src/requests/streamingApi.ts
As the error messages are streamed in the /stream endpoint, it gets rendered in the query response to the user
Suitable response to the user in case of error.
> React widget: Sync with the Stream endpoint, error handling

- docs/pages/Extensions/react-widget.md
- docs
- Updated documentation of the widget with the new updates to the widget
> Widget Documentation update

- extensions/react-widget/package.json
- extensions/react-widget/publish.sh
- extensions/react-widget/src/components/DocsGPTWidget.tsx
- extensions/react-widget/src/types/index.ts
* adding "large" option for widget size prop.
* adding publish.sh to automate the process for publishing docsgpt-react and docsgpt npm packages simultaneously.
* More flexible sizes for integrating widgets to client web apps.
To test publish.sh
* Run `./publish.sh`
* Run `chmod +x publish.sh` if the ownership conflicts on system.
> React-widget: Adding "large" option for widget size

- frontend/package-lock.json
- frontend/package.json
- frontend/src/Navigation.tsx
- frontend/src/components/Dropdown.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- frontend/src/locale/en.json
- frontend/src/modals/DeleteConvModal.tsx
- frontend/src/preferences/APIKeyModal.tsx
- frontend/src/upload/Upload.tsx
This PR addresses two issues:
1. Fixes the [CSV file upload issue](https://github.com/arc53/DocsGPT/issues/1106).
Additional info and screenshots are attached in the bottom.
2. Resolves a linting issue caused by the incompatibility between prettier 3.3.3 and eslint-plugin-prettier 4.2.1. This is a known [issue](https://github.com/prettier/eslint-plugin-prettier/issues/562). Upgrading eslint-plugin-prettier to version 5.x resolved the problem. The upgrade also required formatting the files to pass lint checks.
Note: The GitHub action was blocking commits, so the fix for eslint-plugin-prettier and the related updates were included in this PR. Please let me know if we should open a separate issue for this …
> CSV upload

- extensions/react-widget/package-lock.json
- extensions/react-widget/package.json
- extensions/react-widget/publish.sh
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
* As per the current logic, the `endMessageRef` was referred while scrolling
* In this PR, referring to the `conversationRef` alone to control scrolling
* The `scrollIntoView` method should handle the following cases:
- When the status is `idle` or a new  prompt is just added: Smoothly scroll to the bottom of `conversationRef`
- While streaming: when the response is getting generated, the scroll should stick to the bottom of the conversation container, to make the streaming more consistent.
* Frictionless streaming.
Fixed the overflow of code, without any language match.
Minor change in …
> Refining the scrolling functionality while streaming

- frontend/package-lock.json
- frontend/package.json
- frontend/src/conversation/ConversationBubble.tsx
This PR adds a new feature that lets users view math equations in Markdown.
- **Why was this change needed?**  
This change is important because it makes it easier for users to add math equations in the Markdown content created by the LLM. Many users wanted better support for math notation, and this feature meets that need. Closes #1175.
- **Other information:**  
The implementation includes a `preprocessLaTeX` function that changes LaTeX symbols so they show up correctly in the Markdown output. We also added plugins like `remark-math` and `rehype-katex` to help with processing and displaying LaTeX.
> feat: Add support for mathematical equations in Markdown

- frontend/src/locale/en.json
- frontend/src/locale/es.json
- frontend/src/locale/jp.json
- frontend/src/locale/zh.json
- frontend/src/settings/APIKeys.tsx
- frontend/src/settings/Documents.tsx
Feature update: Added a "No existing ..." messages in multiple locales (English, Spanish, Japanese, and Chinese), and updated both the `APIKeys.tsx` and `Documents.tsx` components to display a message when there are no API keys or documents available.
- **Why was this change needed?**  
related to #1169. This change was needed to improve user experience by providing feedback when there are no existing chatbots or documents in their respective sections, ensuring users are clearly informed when no data is available across multiple languages.
> Feat(1169): Handle state of empty tables

- application/vectorstore/faiss.py
- Refactor `FaissStore` to enhance error handling.
- Improve type hints for method signatures.
- Add method documentation for better clarity and maintainability.
- Enhance the initialization process to handle exceptions gracefully.
- Ensure robust loading and creation of the FAISS index.
- Aim to improve usability and facilitate future development.
> Refactor FaissStore to enhance error handling, add improve type hints, and document methods for better maintainability and usability

- application/api/user/routes.py
- application/parser/remote/github_loader.py
- application/parser/remote/remote_creator.py
- frontend/src/locale/en.json
- frontend/src/locale/es.json
- frontend/src/locale/jp.json
- frontend/src/locale/zh.json
- frontend/src/upload/Upload.tsx
Remote github loader
To load code from github
> Github remote loader

- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/conversationSlice.ts
Basically conversationId is updated in two situations:
1. switching the conversation
2. streaming when data.type = 'id'
As per the current flow, there are following bugs:
- While streaming, switching to New Chat, crashes the application
- In case of New Chat, the conversations are not updating in the sidebar
Fix:
- Pause the update of streaming query without pausing the fetchAnswer middleware explicitly.
* Set the status as idle for every update to conversationId
* Append the streaming answer to the response only when the status is not idle.
- Fixes the root cause of the problem.
> Bug Fix: Crash, abnormal update while switching conversation Ids

- frontend/src/components/SettingsBar.tsx
- frontend/src/settings/index.tsx
Here’s a concise and humanized response based on the changes:
This PR introduces a feature that refactors the settings navigation to include a scrollable `SettingsBar` component, improving usability on smaller screens and making the tab navigation more intuitive. related to #1228 
- **Why was this change needed?**  
The previous tab navigation had a limited UX on mobile devices. This change simplifies the codebase, enhances mobile navigation, and improves maintainability by reusing the new `SettingsBar` component.
- **Other information**:  
The scroll functionality adjusts automatically, showing or hiding gradients based on scroll position, enhancing the visual feedback for users.
> Feat(1228) mobile settings menu

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
Removed @vercel/analytics from frontend due to being flagged by AdBlocker, causing rendering issues in the development.
(It is not affecting in Cloud version, neither in build)
- Uninstalled @vercel/analytics from the frontend only also removed importing statement of inject and calling it.
- It was affecting rendering and no error in the console (check the Screenshots) if the AdBlocker extension is enabled, but it starts rendering if you disable it, so if someone is not aware of might be time taking process and check for various setup if it is problem with that. 
> Removed @vercel/analytics from frontend

- frontend/src/Navigation.tsx
Solves issue #1221
Made the logo clickable to improve the overall user experience
It is a common practice to make the logo click redirect to an index page. as stated in #1221 
NA
@pabik please review and merge this PR
> Make logo clickable

- application/api/answer/routes.py
- application/llm/groq.py
- application/llm/llm_creator.py
Feature: Added support for GROQ llms.
To access Groq models via API key
Closes #1206
> Groq llms added

- .github/workflows/ci.yml
- .github/workflows/cife.yml
- .github/workflows/docker-develop-build.yml
- .github/workflows/docker-develop-fe-build.yml
This PR introduces a feature update related to #273. It updates the GitHub workflows to build and push Docker images, including changes in the `ci.yml`, `cife.yml` files, and adds new workflows (`docker-develop-build.yml` and `docker-develop-fe-build.yml`) to support development builds.
- **Why was this change needed?**  
The changes were needed to streamline the CI/CD pipeline for DocsGPT, enabling the release-based tagging and pushing of Docker images. This also adds support for development builds of both the main DocsGPT application and the frontend, ensuring that images can be built in between releases under `develop` tag and pushed to Docker Hub and GitHub Container Registry (GHCR). This allows for better management of both release …
> Feat(273): CI enable images tagging

- frontend/src/locale/i18n.ts
- frontend/src/locale/zh-TW.json
Add Traditional Chinese(zhTW) locale
More language support, more users approach
None
> Add Traditional Chinese(zhTW) locale

- docs/README.md
Yarn dev by default runs the application on port 3000. Changed the port accordingly in readme to maintain consistency.
- **What kind of change does this PR introduce?** (
Docs Update
- **Why was this change needed?**
Docs were inconsistent with actual behaviour.
Fixes #1250
None
> Update localhost port to 3000 in readme

- frontend/src/components/RetryIcon.tsx
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
This PR changes the size of the retry button when on mobile and also hides the "Retry" text so the UI looks more viewable.
This was to fix issue #1230 where the retry button being too big in mobile view
Initial change makes it look like this. If this way of approaching is fine can edit the styles for it to make it look better.
> Fix formatting of mobile retry button

- frontend/src/App.tsx
The PR addresses the screen size issue for medium (md) devices when transitioning from small devices, which caused the textarea to drop down and the scroll to get stuck. The main problem was with the upload modal, and the PR updates the screen height to fix it.
This change fixes #1291
https://github.com/user-attachments/assets/e3c3980f-ff26-4cdc-a79c-20d4156aaa99
> fix: height for md-devices

- application/api/user/routes.py
Refactoring
We can use the `inputs.boolean` from flask-restx [^1] to parse boolean for us. This way `is_promptable` is a `bool` variable and not a `str` variable so we don't need to do `.lower() == "true"` everywhere.
[^1]: https://flask-restx.readthedocs.io/en/latest/api.html?highlight=boolean#flask_restx.inputs.boolean
> refactor(user/routes): simplify parsing of isPromptable

- application/api/user/routes.py
* Steps to reproduce this bug:
1. Create a conversation
2. Create a shared link for the conversation, with enable allow users to prompt further
3. Create another shared link for the conversation, this time disable the option to prompt further
* Current behaviour: The same uuid is assigned to both the shared conversations 
* Expected behaviour: A shared conversation which is promptable with a particular doc should be unique avoiding redundant entries; while a non-promptable shared conversation should also be unique but distinct from a promptable one
Avoids ambiguity in the behaviour of shared conversations.
> Bug fix: /api/share route 

- extensions/react-widget/src/components/DocsGPTWidget.tsx
Fixes #1283
The widget on `docs.docsgpt.cloud` used to print undefined before printing an answer
> Bug Fix: react web widget prints undefined before printing an answer.

- application/api/user/routes.py
- application/parser/file/bulk.py
- application/parser/file/json_parser.py
- frontend/src/index.css
- frontend/src/locale/en.json
- frontend/src/locale/es.json
- frontend/src/locale/jp.json
- frontend/src/locale/zh-TW.json
- frontend/src/locale/zh.json
- frontend/src/upload/Upload.tsx
Feature
Implemented a JSONParser for interacting with `.json` files.
https://github.com/user-attachments/assets/a442ea38-ff2c-487d-be47-917c22f243aa
> feat: JSON Parser Implementation

- application/api/user/routes.py
- application/requirements.txt
- application/tts/base.py
- application/tts/google_tts.py
* Adding `/api/tts` endpoint to get audio_base64 in the response
* Created abstraction in application/tts, with GoogleTTS for conversion to Audio with in-memory storage.
#1202 
*Request body*
Method: POST
```
{
text:"Hi, How are you?"
}
```
*Response body*
```
{
success:true,
audio_base64: "//OExAAAAAAAAAAAAA....",
lang:"en"
}
```
> Add endpoint for Text-To-Speech conversion

- extensions/discord/bot.py
> fix: discord bot

- extensions/discord/bot.py
> fix: bot chunking

- application/api/answer/routes.py
- application/api/internal/routes.py
- application/api/user/routes.py
- application/core/mongo_db.py
- application/usage.py
- application/worker.py
- frontend/src/locale/en.json
- frontend/src/locale/es.json
Adds a file core/mongo_db.py for the singleton class of pymongo client which is used to get connections across all files and no extra connection is created.
Closes #1170
> refactor: use MongoDB singleton for connection management

- frontend/src/index.css
Bug Fix
- **Why was this change needed?**
Fixes #1223
> Fix: Fonts on Safari browser

- application/api/user/routes.py
- application/parser/file/bulk.py
- application/parser/file/pptx_parser.py
- application/requirements.txt
- frontend/src/locale/en.json
- frontend/src/locale/es.json
- frontend/src/locale/jp.json
- frontend/src/locale/zh-TW.json
- frontend/src/locale/zh.json
- frontend/src/upload/Upload.tsx
Feature
This feature introduces a parser for .pptx files, allowing users to interact with presentations. The text in the slides are extracted using python-pptx package.
Demo:
https://github.com/user-attachments/assets/52d56a32-c985-401e-86ee-b6c0329157ce
> feat: `.pptx` Presentation parser implementation

- application/api/user/routes.py
- frontend/src/Navigation.tsx
- frontend/src/api/services/userService.ts
- frontend/src/conversation/ConversationBubble.tsx
- frontend/src/preferences/preferenceApi.ts
- frontend/src/settings/Documents.tsx
* added querying on /combine route to sort according to the given fields(date & tokens)
* default sorting is on data in descending order
* fix - Nav sidebar pops over active upload modal
* fix - text overflows from Sources in the Sources sidebar
* adds functionaity in cadet sort icon
> Adding sorting in documents, minor UI changes

- application/requirements.txt
- application/vectorstore/milvus.py
Bug fix for milvus. 
1. Comma missing
2. argument `filter` is not in the `_docsearch.similarity_search()`, instead , we can use `expr` 
3. add dependency inrequirements.txt
> fix milvus issues

- frontend/src/conversation/conversationSlice.ts
> fix: pending sources even when no sources provided

- extensions/react-widget/src/components/DocsGPTWidget.tsx
> feat: widget bounciness

- frontend/src/conversation/Conversation.tsx
Fixes: #1219 
Before : 
After:
Better UI/UX
Feel free to ask if anymore changes required
> fix: #1219 Too big top margin of message box separator

- frontend/src/Navigation.tsx
- frontend/src/modals/ConfirmationModal.tsx
- frontend/src/modals/CreateAPIKeyModal.tsx
- frontend/src/modals/ShareConversationModal.tsx
- frontend/src/modals/WrapperModal.tsx
- frontend/src/modals/types/index.ts
- frontend/src/settings/Documents.tsx
- frontend/src/upload/Upload.tsx
this pr introduces a wrapper modal, which will act as a base for every other modals. includes functionality to close the modal on a click outside the modal or an `ESC` key press.
fixes: #1231 
> feat: wrapper modal

- application/api/user/routes.py
- application/celery_init.py
- frontend/src/components/DocumentPagination.tsx
- frontend/src/components/DropdownMenu.tsx
- frontend/src/index.css
- frontend/src/preferences/preferenceApi.ts
- frontend/src/settings/APIKeys.tsx
- frontend/src/settings/Documents.tsx
- #1440 
uniform table nicely
update table styling uniformly
@ManishMadan2882
> Table Styling & Add search feature to backend

- application/api/user/routes.py
- frontend/src/conversation/Conversation.tsx
- frontend/src/conversation/ConversationBubble.tsx
- frontend/src/conversation/conversationSlice.ts
- frontend/src/settings/Documents.tsx
- frontend/src/utils/stringUtils.ts
Minor UI adjustments:
-  Code used to overflow in the conversation bubble when there was no match for language
-  The input field in Conversation touched the bottom of the viewport in mobile screens.
-  Font size in the user questions looked larger in mobile browsers.
- Limited characters in Settings/Docs in table column document name to avoid overflows
- In `api/delete_old` remove docs from the collection even if they are missing from the file tree.
UI
> Minor UI adjustments

- application/requirements.txt
* Latest version of `httpx==0.28.1`
* `anthropic==0.40.0` and `openai==1.55.3` are compatible with httpx
Fixes the error mentioned.
> Fixes: Client.__init__() got an unexpected keyword argument 'proxies'

- application/api/answer/routes.py
- application/core/settings.py
- application/retriever/brave_search.py
- application/retriever/classic_rag.py
- application/retriever/duckduck_search.py
- application/utils.py
- frontend/package-lock.json
1. Trims the conversational history to the number of latest queries not more than finite number of tokens(default 500)
Prevents LLM from getting overloaded with large context of history.
> Limiting Conversational history

- frontend/src/components/Input.tsx
- frontend/src/components/ToggleSwitch.tsx
- frontend/src/components/types/index.ts
- frontend/src/upload/Upload.tsx
- frontend/src/upload/types/ingestor.ts
-  Separate the configurations for different remote upload options by structuring interfaces.
-  Adding form schema to generate form elements dynamically based on the `IngestorType`
- Form fields are rendered as 
- `string/number` as `Input` component
-  `boolean` as `ToggleSwitch` component
- `enums` as `Dropdown` component
Maintenance
> Refactor: Ingestor types for remote resources in Upload Component

- application/Dockerfile
- application/vectorstore/base.py
- setup.sh
Hi everyone, my name is Michele and I wanted to contribute to the realization of the project, I forked this one. Read the README.md file, set the development environment. Having analyzed the various issues to start from, I chose #1445
I analyzed the project with the terminal command, 
```
grep -rnw './' -e 'model' --exclude-dir=venv
grep -rnw './' -e 'models' --exclude-dir=venv
```
Thus finding reference to model. 
I modified the following files, 
- applications/Dockerfile
- applications/vectorstore/base.py
- setup.sh
Next I tested the app with commands:
`./setup.sh `
`./run-with-docker-compose.sh`
The app worked without any problems, I hope this problem has been solved, with this I would really like to participate in the project, it is truly fantastic for me.
Otherwise I hope to be able …
> Fixing issues #1445

- setup.sh
This addresses the SC2034 warning.
Uses the underscore `_` instead of `i` in the _waiting for docker loop_ in `setup.sh`.
Because of _pure esthetics_. But it also resolved the [`SC2034`](https://www.shellcheck.net/wiki/SC2034) ShellCheck warning.
N/A
> style: use underscore for an unused loop variable

- frontend/src/conversation/ConversationBubble.tsx
Improved edit message interface and decreased right margin hover on message button
Fixes - #1513 
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Improved edit message interface

- application/api/answer/routes.py
- application/llm/llm_creator.py
- application/llm/novita.py
- setup.sh
Feature: Added support for novita llms
To access Novita llm cloud provider via api key
closes #1688
> feat: novita llms support

- application/llm/openai.py
Bug fix for the AzureOpenAILLM signature 
The create_llm(cls, type, api_key, user_api_key, *args, **kwargs). in **llm_creator.py** has different signature 
AzureOpenAILLM accepts 
def __init__(
self, openai_api_key, openai_api_base, openai_api_version, deployment_name
):
https://github.com/arc53/DocsGPT/issues/1699
Also Class AzureOpenAI from openai package also does not have param "deployment_name"
Causing 
[2025-03-14 03:22:19,182] ERROR in routes: /api/answer - error: AzureOpenAILLM.init() missing 2 required positional arguments: 'openai_api_version' and 'deployment_name' - traceback: Traceback (most …
> fix signature for AzureOpenAILLM

- application/parser/file/tabular_parser.py
- bug fix
https://github.com/arc53/DocsGPT/issues/1526
csv/xlsx file headers was not included when parsing.
> fix[csv_parser]:missing header

- application/api/answer/routes.py
> fix: thought param in /api/answer

- frontend/src/conversation/ConversationBubble.tsx
Questions will be clamped to first 4 lines until expanded to their full height, adding a button to toggle between collapsed and expanded question bubbles
closes #1841
> Collapsible Question bubbles

- application/api/user/routes.py
> fix: replace secure_filename with safe_filename for attachment handling

- README.md
- docs/pages/Deploying/DocsGPT-Settings.mdx
- package-lock.json
- **Documentation update**:  
Expands and clarifies the documentation for configuring `AUTH_TYPE` and available authentication methods in DocsGPT.
---
- Improves the user experience (UX) by making it easier to understand and configure authentication in DocsGPT.
- Addresses [issue #1882](https://github.com/arc53/DocsGPT/issues/1882):  
> "Add a separate docs page to talk about configuring AUTH_TYPE and methods of auth available."
- The previous documentation was either missing, unclear, or not easily discoverable for new users.
---
- The `AUTH_TYPE` section in `DocsGPT-Settings.mdx` now includes:
- A summary table of supported authentication methods (`None`, `simple_jwt`, `session_jwt`)
- Clear configuration examples for each method
- Usage instructions and security notes
- Details on …
> Docs: Expand and Clarify AUTH_TYPE Configuration and Authentication Methods (#1882)

- application/api/answer/routes/stream.py
- application/vectorstore/qdrant.py
> fix: qdrant issues

- application/api/user/routes.py
Fixes unintended behaviour with shared agents:
* user A creates an agent with specific prompt, shares it publicly
* user B queries, and the response is noticed form the default prompt
* functionality
Logging queries generated with a shared agent generated with a custom prompt and custom source
before
```
[2025-08-08 18:00:27,160] INFO in google_ai: GoogleLLM: Message 0: role=system, content_preview=[Part(video_metadata=None, thought=None, code_execution_result=None, executable_code=None, file_data=None, function_call=None, function_response=None, inline_data=None, text="You are a helpful AI assi...
``` …
> Fixes missing attributes on shared agents

- frontend/src/conversation/ConversationBubble.tsx
- **What kind of change does this PR introduce?**
This change introduces a fix to the buttons in the response bubbles of the chat UI. The buttons are always visible now and not just upon hovering. Replicated chatGPT like functionality.
- **Why was this change needed?**
https://github.com/arc53/DocsGPT/issues/1919
Some more suggestions can be taken up later:
1. Text font size for user and assistant message is different (14px and 16px respectively) in mobile view.
2. Copy btn should also have a hover effect similar to other buttons.
> fix: always show the response bubble buttons.

- README.md
- application/api/connector/routes.py
- application/core/settings.py
- application/parser/connectors/google_drive/auth.py
**Update the redirect URL in the GCP with `http://127.0.0.1:7091/api/connectors/callback` for testing locally**
- OAuth state-handling to the existing connector_sessions collection so we can reliably associate the authenticated Google account with the initiating
- The route `/api/connectors/callback` refers to the same mongodb document for the user and provider
- simplified a minor thing so that we use the exact redirect url as in the settings in the GCP; URL is now passed as state not args
fixes the error while authenticating with google drive 
mongodb states
* pending user
```
{
"_id": {
"$oid": …
```
> OAuth fix for connector 

- application/storage/local.py
Fixes #2009
- Bug Fix.  Previously, the local save_file function didn’t accept kwargs, causing a crash when passed extra params (by api/user/agents/routes.py). Added support to maintain consistency with AWS version.
- To be able to create agents locally, without configuring aws storage
> fix: handle missing kwargs in local save_file (Fixes #2009)

- docs/pages/Deploying/Development-Environment.mdx
docs update
To make sure that the embeddings model is placed in the right folder. The project searches for the model in ./models or /app/models
> correct path for storing embeddings model

- frontend/src/Navigation.tsx
Fixes #2043 The spinner in the conversation list (navigation section) was reverted. Previously, the loader color matched the theme, making it invisible or hard to notice.
The spinner was not clearly visible due to its color blending with the theme, affecting user experience.
This fix ensures better visibility of the loader, improving UI clarity during loading states.
> bug fix: spinner to match theme (dark/light) in navigation

- frontend/src/agents/SharedAgentCard.tsx
issue: https://github.com/arc53/DocsGPT/issues/2034
The bug was that an empty obj evaluates to true, hence rendering the empty div and its css.
perfectly centered, as all things should be :P
> fix(ui): centered title due to improper obj check
